mongo.connectionString = "mongodb+srv://ochi130325:vhQgutjpZvARhADi@cluster0.731d7hs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
mongo.database = "user_data" # 任意のDB名（例: bulletin_board）